app/models.py
from flask_login import UserMixin
from . import db

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True) # primary keys are required by SQLAlchemy
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    name = db.Column(db.String(1000))

app/__init__.py
from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    
    app.config['SECRET_KEY'] = 'here goes secret_key'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    
    db.init_app(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    from .models import User
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))   

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

#from app import routes

app/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash
from .models import User
from . import db

auth = Blueprint('auth', __name__)

@auth.route('/login')
def login():
    return render_template('login.html')

@auth.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()

    if not user or not check_password_hash(user.password, password):
        flash('Please check your credentials!')
        return redirect(url_for('auth.login'))
    # if we got here, user exists and knows his password!
    login_user(user, remember=remember)
    return redirect(url_for('main.profile'))

@auth.route('/signup')
def signup():
    return render_template('signup.html')

#@auth.route('/signup', methods=['POST'])
#def signup_post():
#    email = request.form.get('email')
#    name = request.form.get('name')
#    password = request.form.get('password')

#    user = User.query.filter_by(email=email).first() #if this get a user, this means user already registered and must be redirected to the login page
#    if user:
#        flash('User already registered!')
#        return redirect(url_for('auth.signup'))
    # if we reached here, it's time to add the user to the DB
#    new_user = User(email=email, name=name, password=generate_password_hash(password, method='sha256'))
#    db.session.add(new_user)
#    db.session.commit()
    
#    return redirect(url_for('auth.login'))

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

app/main.py
from flask import Blueprint, render_template, request, url_for
from flask_login import login_required, current_user
from datetime import datetime, timedelta
from . import db
import os

main = Blueprint('main', __name__)

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/profile')
@login_required
def profile():
    now = datetime.now()
    cam_name = []
    for i in os.scandir('./app/static/streams'):
        if i.is_dir():
            cam_name.append(i.name)
    date = [(now - timedelta(i)).strftime('%d/%m/%Y')
 for i in range(7)]
    return render_template('profile.html',
	date = date, cam_name = cam_name, name=current_user.name)

@main.route('/profile', methods=['POST'])
@login_required
def profile_post():
    data = request.form
    cam_name = []
    for i in os.scandir('./app/static/streams'):
        if i.is_dir():
            cam_name.append(i.name)
    #time to count chosen weekday
    chosen = str((datetime.now().weekday() - int(data["date"]))%7 + 1)
    cam_index = int(data['cam']) - 1
    dir_name = cam_name[cam_index]
    # BIG dir name means there is only one weekday
    if dir_name.isupper:
        chosen = ''
    file_list ={}
    for filename in os.scandir('./app/static/streams/' + dir_name):
        if filename.is_file() and filename.name.endswith(f'{chosen}.mkv'):
           file_list.update({filename.name:datetime.fromtimestamp(filename.stat()[-1]).strftime('%d%m%Y: %H%M')})
    file_list = sorted(file_list.items())
    urls = [url_for('static', filename='streams/' + dir_name + '/' +i[0]) for i in file_list]
    times = [i[1] for i in file_list]
    print(f'urls:{urls}')
    return render_template('playback.html', filename=urls, times=times)    

app/routes.py
from app import app
from datetime import datetime
from datetime import timedelta
from flask import render_template
from flask import request, url_for
import os

@app.route('/')
def index():
    now = datetime.now()
    cam_name = []
    for i in os.scandir('./app/static/streams'):
        if i.is_dir():
            cam_name.append(i.name)
    date = [(now - timedelta(i)).strftime('%d/%m/%Y')
 for i in range(7)]
    return render_template('index.html',
	date = date, cam_name = cam_name)

@app.route('/', methods = ['POST'])
def parse_request():
    data = request.form
    cam_name = []
    for i in os.scandir('./app/static/streams'):
        if i.is_dir():
            cam_name.append(i.name)
    #time to count chosen weekday
    chosen = str((datetime.now().weekday() - int(data["date"]))%7 + 1)
    cam_index = int(data['cam']) - 1
    dir_name = cam_name[cam_index]
    # BIG dir name means there is only one weekday
    if dir_name.isupper:
        chosen = ''
    file_list ={} 
    for filename in os.scandir('./app/static/streams/' + dir_name):
        if filename.is_file() and filename.name.endswith(f'{chosen}.mkv'):
           file_list.update({filename.name:datetime.fromtimestamp(filename.stat()[-1]).strftime('%d%m%Y: %H%M')}) 
    file_list = sorted(file_list.items()) 
    urls = [url_for('static', filename='streams/' + dir_name + '/' +i[0]) for i in file_list]
    times = [i[1] for i in file_list]
    print(f'urls:{urls}')
    return render_template('playback.html', filename=urls, times=times) #have to make return exit and separate html template

app/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>VCloud</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
</head>

<body>
    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">

                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('main.index') }}" class="navbar-item">
                                Home
                            </a>
			{% if current_user.is_authenticated %}
                            <a href="{{ url_for('main.profile') }}" class="navbar-item">
                                Profile
                            </a>
			{% endif %}
			{% if not current_user.is_authenticated %}
                            <a href="{{ url_for('auth.login') }}" class="navbar-item">
                                Login
                            </a>
			{% endif %}
			{% if not current_user.is_authenticated %}
                            <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                                Sign Up
                            </a>
			{% endif %}
			{% if current_user.is_authenticated %}
                            <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                                Logout
                            </a>
			{% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  VCloud home page
</h1>
<h2 class="subtitle">
  Proceed to login to access data
</h2>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
	{% with messages = get_flashed_messages() %}
	{% if messages %}
    		<div class="notification is-danger">
        	{{ messages[0] }}
    		</div>
	{% endif %}
	{% endwith %}
        <form method="POST" action="/login">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Your Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Your Password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox">
                    Remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}

app/templates/playback.html
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<title>Playback screen</title>
</head>

<div class="container">
  <h2>Table</h2>
  <div class="table-responsive">          
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Time</th>
        <th>Record</th>
      </tr>
    </thead>
    <tbody>
{% for i in filename%}
<tr>
        <td>{{ loop.index }}</td>
        <td>{{times[loop.index]}}</td>
        <td>
	<video width="320" height="240" controls="controls" preload="preload">
	<source src={{ i }} type="video/mp4"></source>
	</video>
	</td>
</tr>
{% endfor %}
    </tbody>
  </table>
  </div>
</div>

</body>
</html>

app/templates/profile.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Welcome to the home DVR system, {{ name }}!
</h1>
<h2>
  Today is {{date.0}}
</h2>
<form action="/profile" method="POST">
        <p><select name="cam">
                {% for i in cam_name%}
                <option value={{ loop.index }}>{{ i }}
                {% endfor %}
        </select>
        <p><select name="date">
                <option selected value="0">{{date.0}}</option>
                <option value="1">{{date.1}}</option>
                <option value="2">{{date.2}}</option>
                <option value="3">{{date.3}}</option>
                <option value="4">{{date.4}}</option>
                <option value="5">{{date.5}}</option>
                <option value="6">{{date.6}}</option>
        </select>
        <input type="submit" value="Open"></p>
</form>

{% endblock %}

app/templates/signup.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
	{% with messages = get_flashed_messages() %}
	{% if messages %}
    		<div class="notification is-danger">
        	{{ messages[0] }}. Go to <a href="{{ url_for('auth.login') }}">login page</a>.
    		</div>
	{% endif %}
	{% endwith %}
        <form method="POST" action="/signup">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="name" placeholder="Name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}